targets:
  $default:
    builders:
      objectbox_generator|objectbox_generator:
        generate_for:
          include:
            - lib/**.dart
            - lib/**.dart
            - lib/**.dart
